import { useState, useEffect } from 'react';
import { useNavigate, useSearchParams } from 'react-router-dom';
import { supabase } from '../api/supabase';
import { motion, AnimatePresence, Reorder } from 'framer-motion';
import { Plus, Trash2, Check, ArrowLeft, Save, Dumbbell, Loader2, Timer, ChevronDown, TimerOff, GripVertical } from 'lucide-react';
import type { Exercise } from '../types';
import ExerciseMarketplace from '../components/marketplace/ExerciseMarketplace';
import AutoRoutineGenerator from '../components/workout/AutoRoutineGenerator';
import MediaModal from '../components/shared/MediaModal';
import ConfirmationModal from '../components/shared/ConfirmationModal';
import { Helmet } from 'react-helmet-async';
import { useNotification } from '../context/NotificationContext';

interface WorkoutExerciseState {
  id: string;
  exercise: Exercise;
  sets: {
    weight: string;
    reps: string;
    completed: boolean;
  }[];
}

const WorkoutEditor = () => {
  const navigate = useNavigate();
  const [name, setName] = useState('Nuevo Entrenamiento');
  const [exercises, setExercises] = useState<WorkoutExerciseState[]>([]);
  const [marketMode, setMarketMode] = useState<'add' | 'replace' | null>(null);
  const [replaceExId, setReplaceExId] = useState<string | null>(null);
  const [showAutoGenerator, setShowAutoGenerator] = useState(false);
  const [showDeleteConfirm, setShowDeleteConfirm] = useState(false);
  const [saving, setSaving] = useState(false);
  const [loading, setLoading] = useState(false);
  const [isTemplate, setIsTemplate] = useState(false);
  const [expandedEx, setExpandedEx] = useState<string | null>(null); // Use a unique string key
  
  // Timer State
  const [timeLeft, setTimeLeft] = useState<number | null>(null);
  const [isTimerActive, setIsTimerActive] = useState(false);
  const [timerDuration] = useState(60);
  
  // Fullscreen Preview State
  const [fsMedia, setFsMedia] = useState<{ url: string; title: string } | null>(null);
  
  const [searchParams, setSearchParams] = useSearchParams();
  const { showToast } = useNotification();

  // Request notifications permissions on mount
  useEffect(() => {
    if ('Notification' in window && Notification.permission === 'default') {
      Notification.requestPermission();
    }
  }, []);

  // Restore timer state on mount
  useEffect(() => {
    const savedEnd = localStorage.getItem('workout_timer_end');
    if (savedEnd) {
      const end = parseInt(savedEnd, 10);
      const now = Date.now();
      const remaining = Math.round((end - now) / 1000);
      if (remaining > 0) {
        setTimeLeft(remaining);
        setIsTimerActive(true);
      } else {
        localStorage.removeItem('workout_timer_end');
        localStorage.removeItem('workout_timer_duration');
      }
    }
  }, []);

  // Tab Visibility Sync
  useEffect(() => {
    const handleVisibilityChange = () => {
      if (document.visibilityState === 'visible') {
        const savedEnd = localStorage.getItem('workout_timer_end');
        if (savedEnd) {
          const end = parseInt(savedEnd, 10);
          const now = Date.now();
          const remaining = Math.round((end - now) / 1000);
          
          if (remaining > 0) {
            setTimeLeft(remaining);
            setIsTimerActive(true);
          } else {
            setTimeLeft(null);
            setIsTimerActive(false);
            localStorage.removeItem('workout_timer_end');
            localStorage.removeItem('workout_timer_duration');
          }
        }
      }
    };
    document.addEventListener('visibilitychange', handleVisibilityChange);
    return () => document.removeEventListener('visibilitychange', handleVisibilityChange);
  }, []);

  const generateId = () => {
    return `ex_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`;
  };

  useEffect(() => {
    const templateId = searchParams.get('templateId');
    const editId = searchParams.get('editId');
    const isNewTemplate = searchParams.get('template') === 'true';
    
    if (isNewTemplate) {
      setIsTemplate(true);
      setName('Nueva Rutina');
    }

    if (editId) {
      loadWorkoutData(editId, true);
    } else if (templateId) {
      loadWorkoutData(templateId, false);
    }
  }, [searchParams]);

  const handleAutoGenerated = (newExercises: Exercise[]) => {
    const formatted = newExercises.map(ex => ({
      id: generateId(),
      exercise: ex,
      sets: [{ weight: '', reps: '', completed: false }]
    }));
    setExercises([...exercises, ...formatted]);
    setShowAutoGenerator(false);
  };

  // Timer Interval
  useEffect(() => {
    let interval: any;
    if (isTimerActive) {
      interval = setInterval(() => {
        const savedEnd = localStorage.getItem('workout_timer_end');
        if (savedEnd) {
          const end = parseInt(savedEnd, 10);
          const now = Date.now();
          const remaining = Math.round((end - now) / 1000);
          
          if (remaining <= 0) {
            setTimeLeft(0);
            setIsTimerActive(false);
            localStorage.removeItem('workout_timer_end');
            localStorage.removeItem('workout_timer_duration');
            playTimerEndSound();
          } else {
            setTimeLeft(remaining);
          }
        } else {
          setIsTimerActive(false);
          setTimeLeft(null);
        }
      }, 1000);
    }
    return () => clearInterval(interval);
  }, [isTimerActive]);

  const playTimerEndSound = () => {
    try {
      const audio = new Audio('https://assets.mixkit.co/active_storage/sfx/2869/2869-preview.mp3');
      audio.volume = 0.5;
      audio.play();
      
      // Haptic feedback if available
      if (window.navigator.vibrate) {
        window.navigator.vibrate([200, 100, 200]);
      }
    } catch (e) {
      console.warn('Audio play failed', e);
    }
  };

  const loadWorkoutData = async (id: string, isEditing: boolean) => {
    setLoading(true);
    const { data: workout, error: workoutError } = await supabase
      .from('workouts')
      .select('*, workout_exercises(*, exercise:exercises(*), sets(*))')
      .eq('id', id)
      .single();

    if (workoutError || !workout) {
      console.error('Error loading workout data:', workoutError);
      return;
    }

    setName(workout.name);
    setIsTemplate(workout.is_template);
    
    if (!isEditing) {
      setIsTemplate(false);
    }

    interface DBSet { weight: number, reps: number, completed: boolean, order_index: number }

    const loadedExercises: WorkoutExerciseState[] = workout.workout_exercises
      .sort((a: any, b: any) => a.order_index - b.order_index)
      .map((we: any) => ({
        id: we.id,
        exercise: Array.isArray(we.exercise) ? we.exercise[0] : we.exercise,
        sets: (we.sets || []).sort((a: DBSet, b: DBSet) => a.order_index - b.order_index).map((s: DBSet) => ({
          weight: s.weight ? s.weight.toString() : '',
          reps: s.reps ? s.reps.toString() : '',
          completed: s.completed
        }))
      }));

    setExercises(loadedExercises);
    setLoading(false);
  };

  const addExercise = (exercise: Exercise) => {
    setExercises([...exercises, {
      id: generateId(),
      exercise,
      sets: [{ weight: '', reps: '', completed: false }]
    }]);
  };

  const handleMarketSelect = (exercise: Exercise) => {
    if (marketMode === 'replace' && replaceExId) {
      setExercises(exercises.map(ex => {
        if (ex.id === replaceExId) {
           return { ...ex, exercise };
        }
        return ex;
      }));
    } else {
      addExercise(exercise);
    }
    setMarketMode(null);
    setReplaceExId(null);
  };

  const removeExercise = (id: string) => {
    setExercises(prev => prev.filter(ex => ex.id !== id));
  };

  const addSet = (exerciseId: string) => {
    setExercises(prev => prev.map(ex => {
      if (ex.id !== exerciseId) return ex;
      const lastSet = ex.sets[ex.sets.length - 1];
      return {
        ...ex,
        sets: [...ex.sets, {
          weight: lastSet?.weight || '',
          reps: lastSet?.reps || '',
          completed: false
        }]
      };
    }));
  };

  const removeSet = (exerciseId: string, setIndex: number) => {
    setExercises(prev => prev.map(ex => {
      if (ex.id !== exerciseId) return ex;
      if (ex.sets.length <= 1) return ex; // Keep at least one set
      return {
        ...ex,
        sets: ex.sets.filter((_, i) => i !== setIndex)
      };
    }));
  };

  const updateSet = (exerciseId: string, setIndex: number, field: keyof WorkoutExerciseState['sets'][0], value: string | boolean) => {
    setExercises(prev => prev.map(ex => {
      if (ex.id !== exerciseId) return ex;
      return {
        ...ex,
        sets: ex.sets.map((s, i) => {
          if (i !== setIndex) return s;
          return { ...s, [field]: value };
        })
      };
    }));
  };

  const toggleSetComplete = (exerciseId: string, setIndex: number) => {
    setExercises(prev => prev.map(ex => {
      if (ex.id !== exerciseId) return ex;
      
      const newSets = ex.sets.map((s, i) => {
        if (i !== setIndex) return s;
        const isNowCompleted = !s.completed;
        
        // Auto-trigger timer if completing a set
        if (isNowCompleted && !isTemplate) {
          startTimer();
        }
        
        return { ...s, completed: isNowCompleted };
      });

      return { ...ex, sets: newSets };
    }));
  };

  const startTimer = (seconds = timerDuration) => {
    const endTime = Date.now() + seconds * 1000;
    localStorage.setItem('workout_timer_end', endTime.toString());
    localStorage.setItem('workout_timer_duration', seconds.toString());
    
    setTimeLeft(seconds);
    setIsTimerActive(true);

    // Notificar al Service Worker para iniciar temporizador en segundo plano
    if ('serviceWorker' in navigator && navigator.serviceWorker.controller) {
      navigator.serviceWorker.controller.postMessage({
        type: 'START_TIMER',
        duration: seconds
      });
    }
  };

  const stopTimer = () => {
    setIsTimerActive(false);
    setTimeLeft(null);
    localStorage.removeItem('workout_timer_end');
    localStorage.removeItem('workout_timer_duration');

    // Notificar al Service Worker para cancelar temporizador en segundo plano
    if ('serviceWorker' in navigator && navigator.serviceWorker.controller) {
      navigator.serviceWorker.controller.postMessage({
        type: 'CANCEL_TIMER'
      });
    }
  };

  const adjustTimer = (seconds: number) => {
    const savedEnd = localStorage.getItem('workout_timer_end');
    let newTimeLeft = seconds;
    
    if (savedEnd) {
      const end = parseInt(savedEnd, 10);
      const remaining = Math.round((end - Date.now()) / 1000);
      newTimeLeft = Math.max(0, remaining + seconds);
    }
    
    const newEndTime = Date.now() + newTimeLeft * 1000;
    localStorage.setItem('workout_timer_end', newEndTime.toString());
    localStorage.setItem('workout_timer_duration', newTimeLeft.toString());
    
    setTimeLeft(newTimeLeft);
    if (!isTimerActive) setIsTimerActive(true);

    // Notificar al Service Worker con el nuevo tiempo ajustado
    if ('serviceWorker' in navigator && navigator.serviceWorker.controller) {
      navigator.serviceWorker.controller.postMessage({
        type: 'START_TIMER',
        duration: newTimeLeft
      });
    }
  };

  const saveWorkout = async () => {
    if (exercises.length === 0) return;
    setSaving(true);
    
    try {
      const { data: { user } } = await supabase.auth.getUser();
      if (!user) throw new Error('Not authenticated');

      const currentEditId = searchParams.get('editId');
      let workoutId = currentEditId;

      // 1. Create or Update Workout
      if (currentEditId) {
        const { error: updateError } = await supabase
          .from('workouts')
          .update({
            name,
            is_template: isTemplate,
            completed_at: isTemplate ? null : new Date().toISOString()
          })
          .eq('id', currentEditId);
        
        if (updateError) throw updateError;

        // Delete existing exercises/sets to re-insert updated ones (cleanest way to handle adds/removes)
        const { error: deleteError } = await supabase
          .from('workout_exercises')
          .delete()
          .eq('workout_id', currentEditId);
        
        if (deleteError) throw deleteError;
      } else {
        const { data: newWorkout, error: workoutError } = await supabase
          .from('workouts')
          .insert({
            user_id: user.id,
            name,
            started_at: new Date().toISOString(),
            completed_at: isTemplate ? null : new Date().toISOString(),
            is_template: isTemplate
          })
          .select()
          .single();

        if (workoutError) throw workoutError;
        workoutId = newWorkout.id;
      }

      // 2. Create Workout Exercises and Sets
      for (let i = 0; i < exercises.length; i++) {
        const { data: we, error: weError } = await supabase
          .from('workout_exercises')
          .insert({
            workout_id: workoutId,
            exercise_id: exercises[i].exercise.id,
            order_index: i
          })
          .select()
          .single();

        if (weError) throw weError;

        const setsToInsert = exercises[i].sets.map((set, setIndex) => ({
          workout_exercise_id: we.id,
          weight: parseFloat(set.weight) || 0,
          reps: parseInt(set.reps) || 0,
          completed: set.completed,
          order_index: setIndex
        }));

        const { error: setsError } = await supabase
          .from('sets')
          .insert(setsToInsert);

        if (setsError) throw setsError;
      }

      showToast(isTemplate ? 'Rutina guardada con éxito' : 'Entrenamiento guardado con éxito', 'success');
      
      // Update URL if it was a new workout, but STAY on the page
      if (!currentEditId) {
        const params = new URLSearchParams(window.location.search);
        params.set('editId', workoutId!);
        setSearchParams(params, { replace: true });
      }
    } catch (err) {
      console.error(err);
      showToast('Error al guardar', 'error');
    } finally {
      setSaving(false);
    }
  };

  const deleteWorkout = async () => {
    const editId = searchParams.get('editId');
    if (!editId) return;
    
    setSaving(true);
    try {
      const { error } = await supabase
        .from('workouts')
        .delete()
        .eq('id', editId);
      
      if (error) throw error;
      showToast('Rutina eliminada', 'success');
      navigate('/routines');
    } catch (err) {
      console.error(err);
      showToast('Error al eliminar', 'error');
    } finally {
      setSaving(false);
      setShowDeleteConfirm(false);
    }
  };

  return (
    <div className="min-h-screen bg-background pb-32">
      <Helmet>
        <title>{name} | FitPlanner Pro</title>
        <meta name="description" content="Registra tus ejercicios, series y repeticiones. Controla tu progreso en tiempo real." />
      </Helmet>
      {/* Header */}
      <div className="fixed top-0 left-0 right-0 glass-card rounded-none border-t-0 p-4 z-40 flex justify-between items-center">
        <button onClick={() => navigate(-1)} className="p-2 bg-white/5 rounded-xl">
          <ArrowLeft size={20} />
        </button>
        <h1 className="flex-1">
          <input 
            value={name}
            onChange={(e) => setName(e.target.value)}
            placeholder={isTemplate ? "Nombre de la Rutina (ej. Pierna)" : "Nombre del Entrenamiento"}
            className="w-full bg-transparent text-center font-black italic uppercase tracking-tighter outline-none focus:text-primary px-4"
            aria-label={isTemplate ? "Nombre de la rutina" : "Nombre del entrenamiento"}
          />
        </h1>
        <div className="flex items-center space-x-2">
          {searchParams.get('editId') && (
            <button 
              onClick={() => setShowDeleteConfirm(true)} 
              disabled={saving}
              className="p-2.5 rounded-xl bg-red-500/10 text-red-500 hover:bg-red-500 hover:text-white transition-all shadow-lg"
              title="Eliminar rutina"
            >
              <Trash2 size={20} />
            </button>
          )}
          <button 
            onClick={saveWorkout} 
            disabled={saving || exercises.length === 0}
            className={`p-2.5 rounded-xl bg-primary text-black hover:scale-105 active:scale-95 transition-all shadow-lg ${saving ? 'animate-pulse' : ''}`}
            title="Guardar cambios"
          >
            <Save size={20} />
          </button>
        </div>
      </div>

      {loading ? (
        <div className="flex flex-col items-center justify-center min-h-[60vh] space-y-4">
          <Loader2 size={48} className="text-primary animate-spin" />
          <p className="text-white/30 font-bold uppercase tracking-widest text-xs">Cargando datos...</p>
        </div>
      ) : (
        <Reorder.Group 
          axis="y" 
          values={exercises.map(ex => ex.id)} 
          onReorder={(newIds) => {
            const newOrder = newIds.map(id => exercises.find(ex => ex.id === id)!);
            setExercises(newOrder);
          }}
          className="pt-20 px-4 space-y-6 max-w-4xl mx-auto w-full"
        >
          <AnimatePresence>
            {exercises.map((ex) => (
              <Reorder.Item 
                key={ex.id} 
                value={ex.id}
                className="relative group transition-all"
              >
                <motion.div 
                  initial={{ opacity: 0, scale: 0.95 }}
                  animate={{ opacity: 1, scale: 1 }}
                  exit={{ opacity: 0, scale: 0.95 }}
                  className="glass-card flex flex-col overflow-hidden border border-white/[0.08] shadow-[0_8px_30px_rgb(0,0,0,0.3)] bg-gradient-to-br from-white/[0.03] to-transparent hover:border-white/20 transition-all duration-300 rounded-3xl w-full"
                >
                  <div className="flex-1 flex flex-col min-w-0">
                    <div 
                      className="p-5 flex justify-between items-center cursor-pointer hover:bg-white/[0.02] transition-all duration-200"
                      onClick={() => {
                        setExpandedEx(expandedEx === ex.id ? null : ex.id);
                      }}
                    >
                      <div className="flex items-center space-x-3 sm:space-x-4 flex-1 min-w-0">
                        {/* Grip Handle / Drag trigger - Styled beautifully inside the card header */}
                        <div 
                          className="text-white/20 hover:text-primary transition-colors cursor-grab active:cursor-grabbing p-1.5 -ml-2 shrink-0"
                          onClick={(e) => e.stopPropagation()}
                        >
                          <GripVertical size={20} />
                        </div>

                        {ex.exercise.video_url || ex.exercise.image_url ? (
                          <div className="w-16 h-16 rounded-2xl overflow-hidden shrink-0 bg-black/40 border border-white/10 relative group/media shadow-md">
                            {ex.exercise.video_url ? (
                              <video src={ex.exercise.video_url} autoPlay loop muted playsInline className="w-full h-full object-cover" />
                            ) : ex.exercise.image_url?.includes('.mp4') || ex.exercise.image_url?.includes('.webm') ? (
                              <video src={ex.exercise.image_url} autoPlay loop muted playsInline className="w-full h-full object-cover" />
                            ) : (
                              <img src={ex.exercise.image_url!} alt={ex.exercise.name} className="w-full h-full object-cover group-hover/media:scale-110 transition-transform duration-300" />
                            )}
                          </div>
                        ) : (
                          <div className="w-16 h-16 rounded-2xl shrink-0 bg-white/5 border border-white/10 flex items-center justify-center text-white/20">
                            <Dumbbell size={24} />
                          </div>
                        )}
                        <div className="flex-1 min-w-0">
                          <h3 className="font-black italic uppercase tracking-tight text-white group-hover:text-primary transition-colors text-base leading-tight truncate">{ex.exercise.name}</h3>
                          <div className="flex items-center space-x-2 mt-1">
                            <div className="w-1.5 h-1.5 rounded-full bg-primary" />
                            <span className="text-[10px] text-white/40 uppercase font-black tracking-widest">{ex.exercise.category}</span>
                          </div>
                        </div>
                      </div>
                      <div className="flex items-center space-x-1">
                        <button 
                          onClick={(e) => {
                            e.stopPropagation();
                            setReplaceExId(ex.id);
                            setMarketMode('replace');
                          }} 
                          className="p-2.5 text-white/30 hover:text-primary hover:bg-white/5 rounded-xl transition-all duration-200"
                          title="Reemplazar ejercicio"
                        >
                          <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round"><path d="M21 12a9 9 0 0 0-9-9 9.75 9.75 0 0 0-6.74 2.74L3 8"/><path d="M3 3v5h5"/><path d="M3 12a9 9 0 0 0 9 9 9.75 9.75 0 0 0 6.74-2.74L21 16"/><path d="M16 21v-5h5"/></svg>
                        </button>
                        <button 
                          onClick={(e) => {
                            e.stopPropagation();
                            removeExercise(ex.id);
                          }} 
                          className="p-2.5 text-white/30 hover:text-red-400 hover:bg-red-500/10 rounded-xl transition-all duration-200"
                          title="Eliminar ejercicio"
                        >
                          <Trash2 size={18} />
                        </button>
                        <div className={`p-2 transition-transform duration-300 ${expandedEx === ex.id ? 'rotate-180 text-primary' : 'text-white/20'}`}>
                          <ChevronDown size={20} />
                        </div>
                      </div>
                    </div>

                    <AnimatePresence initial={false}>
                      {expandedEx === ex.id && (
                        <motion.div
                          initial={{ height: 0, opacity: 0 }}
                          animate={{ height: 'auto', opacity: 1 }}
                          exit={{ height: 0, opacity: 0 }}
                          transition={{ duration: 0.3, ease: 'easeInOut' }}
                          className="overflow-hidden bg-black/10 border-t border-white/[0.04]"
                        >
                          {/* Beautiful Widescreen Image/Video Preview */}
                          {ex.exercise.image_url && (
                            <div className="px-5 pt-5 pb-2">
                              <div 
                                className="aspect-video w-full rounded-2xl overflow-hidden relative flex items-center justify-center bg-black/40 cursor-expand hover:opacity-90 transition-all group/expand border border-white/10 shadow-lg"
                                onClick={(e) => {
                                  e.stopPropagation();
                                  setFsMedia({ 
                                    url: ex.exercise.video_url || ex.exercise.image_url || '', 
                                    title: ex.exercise.name 
                                  });
                                }}
                              >
                                {/* Video detection */}
                                {ex.exercise.video_url ? (
                                  <video 
                                    src={ex.exercise.video_url} 
                                    autoPlay 
                                    loop 
                                    muted 
                                    playsInline 
                                    controls
                                    className="relative z-10 w-full h-full object-cover"
                                  />
                                ) : (ex.exercise.image_url?.includes('.mp4') || 
                                  ex.exercise.image_url?.includes('.webm') || 
                                  ex.exercise.image_url?.includes('video') ||
                                  ex.exercise.image_url?.includes('giphy')) ? (
                                  <video 
                                    src={ex.exercise.image_url} 
                                    autoPlay 
                                    loop 
                                    muted 
                                    playsInline 
                                    controls
                                    className="relative z-10 w-full h-full object-cover"
                                  />
                                ) : (
                                  <img 
                                    src={ex.exercise.image_url || ''} 
                                    alt={ex.exercise.name} 
                                    className="relative z-10 w-full h-full object-cover" 
                                  />
                                )}
                                <div className="absolute inset-0 bg-gradient-to-t from-black/60 via-transparent to-transparent pointer-events-none z-20" />
                              </div>
                            </div>
                          )}

                          {/* Sets Section */}
                          <div className="p-5 space-y-3">
                            {/* Tiny Header */}
                            {ex.sets.length > 0 && (
                              <div className="flex items-center gap-3 px-2 pb-1.5 text-[10px] uppercase font-black tracking-widest text-white/30 border-b border-white/[0.04]">
                                <div className="w-6 text-center">#</div>
                                <div className="flex-1 text-center">KG</div>
                                <div className="flex-1 text-center">Reps</div>
                                <div className="w-10 shrink-0"></div>
                                <div className="w-10 shrink-0"></div>
                              </div>
                            )}

                            {ex.sets.map((set, setIdx) => (
                              <div key={setIdx} className={`flex items-center gap-3 p-2 rounded-2xl transition-all duration-200 ${set.completed ? 'bg-primary/10 border border-primary/20' : 'bg-white/[0.02] border border-white/[0.04] hover:bg-white/[0.04]'}`}>
                                <div className="w-6 text-center text-xs font-black text-white/40">{setIdx + 1}</div>
                                
                                <div className="flex-1">
                                  <input 
                                    type="number"
                                    inputMode="decimal"
                                    placeholder="0"
                                    className="w-full bg-black/60 border border-white/10 rounded-xl py-2 px-1 text-center text-sm font-black outline-none focus:border-primary/50 focus:ring-1 focus:ring-primary/20 transition-all text-white placeholder-white/10"
                                    value={set.weight || ''}
                                    onChange={(e) => updateSet(ex.id, setIdx, 'weight', e.target.value)}
                                  />
                                </div>
                                
                                <div className="flex-1">
                                  <input 
                                    type="number"
                                    inputMode="numeric"
                                    placeholder="0"
                                    className="w-full bg-black/60 border border-white/10 rounded-xl py-2 px-1 text-center text-sm font-black outline-none focus:border-primary/50 focus:ring-1 focus:ring-primary/20 transition-all text-white placeholder-white/10"
                                    value={set.reps || ''}
                                    onChange={(e) => updateSet(ex.id, setIdx, 'reps', e.target.value)}
                                  />
                                </div>

                                <button 
                                  onClick={() => removeSet(ex.id, setIdx)}
                                  className="w-10 h-10 rounded-xl text-white/30 hover:text-red-400 hover:bg-red-400/10 flex items-center justify-center transition-all shrink-0"
                                  title="Eliminar serie"
                                >
                                  <Trash2 size={16} />
                                </button>
                                <button 
                                  onClick={() => toggleSetComplete(ex.id, setIdx)}
                                  className={`w-10 h-10 rounded-xl flex items-center justify-center transition-all shrink-0 ${set.completed ? 'bg-primary text-black shadow-[0_0_15px_rgba(0,242,255,0.4)] scale-105' : 'bg-black/60 border border-white/10 text-white/30 hover:text-primary hover:border-primary/30'}`}
                                  title={set.completed ? "Serie completada" : "Completar serie"}
                                >
                                  <Check size={16} className="stroke-[3]" />
                                </button>
                              </div>
                            ))}

                            <button 
                              onClick={() => addSet(ex.id)}
                              className="w-full py-3 flex justify-center items-center gap-2 border border-dashed border-white/10 hover:border-primary/30 rounded-2xl text-xs font-black uppercase tracking-widest text-white/40 hover:bg-primary/5 hover:text-primary transition-all mt-3"
                            >
                              <span className="text-base leading-none">+</span> Añadir Serie
                            </button>
                          </div>
                        </motion.div>
                      )}
                    </AnimatePresence>
                  </div>
                </motion.div>
              </Reorder.Item>
            ))}
          </AnimatePresence>
            <div className="flex gap-3">
              <button
                onClick={() => setMarketMode('add')}
                className="flex-1 glass-card p-4 flex items-center justify-center space-x-2 border-primary/20 hover:border-primary/50 transition-all text-primary"
              >
                <Plus size={20} />
                <span className="font-bold uppercase italic text-xs">Añadir Ejercicio</span>
              </button>
              <button
                onClick={() => setShowAutoGenerator(true)}
                className="flex-1 glass-card p-4 flex items-center justify-center space-x-2 border-primary/20 hover:border-primary/50 transition-all text-primary"
              >
                <Loader2 size={20} className="text-primary hover:rotate-180 transition-transform" />
                <span className="font-bold uppercase italic text-xs">Auto-Generar</span>
              </button>
            </div>
          </Reorder.Group>
        )
      }

      <AnimatePresence>
        {marketMode !== null && (
          <ExerciseMarketplace 
            mode={marketMode}
            onSelect={handleMarketSelect}
            onClose={() => setMarketMode(null)}
            isOpen={marketMode !== null}
          />
        )}
        {showAutoGenerator && (
          <AutoRoutineGenerator 
            onGenerated={handleAutoGenerated}
            onClose={() => setShowAutoGenerator(false)}
          />
        )}
      </AnimatePresence>

      {/* Fullscreen Media Modal */}
      <MediaModal 
        isOpen={!!fsMedia}
        url={fsMedia?.url || ''}
        title={fsMedia?.title || ''}
        onClose={() => setFsMedia(null)}
      />

      {/* Floating Rest Timer Component */}
      <AnimatePresence>
        {timeLeft !== null && (
          <motion.div
            initial={{ y: 100, opacity: 0 }}
            animate={{ y: 0, opacity: 1 }}
            exit={{ y: 100, opacity: 0 }}
            className="fixed bottom-24 left-4 right-4 z-50 flex justify-center"
          >
            <div className="glass-card shadow-2xl border-primary/20 bg-black/80 backdrop-blur-2xl px-6 py-4 flex items-center space-x-6 min-w-[300px] justify-between">
              <div className="flex items-center space-x-4">
                <div className="relative">
                  <div className="w-12 h-12 rounded-full border-2 border-white/5 flex items-center justify-center">
                    <Timer className={isTimerActive ? "text-primary animate-pulse" : "text-white/20"} size={24} />
                  </div>
                  {/* Simple Progress Ring effect */}
                  <svg className="absolute inset-0 w-12 h-12 -rotate-90">
                    <circle 
                      cx="24" cy="24" r="22" 
                      fill="transparent" 
                      stroke="currentColor" 
                      strokeWidth="2" 
                      strokeDasharray={2 * Math.PI * 22}
                      strokeDashoffset={(1 - (timeLeft / timerDuration)) * 2 * Math.PI * 22}
                      className="text-primary transition-all duration-300"
                    />
                  </svg>
                </div>
                <div>
                  <div className="text-2xl font-black italic tracking-tighter text-white tabular-nums">
                    {Math.floor(timeLeft / 60)}:{(timeLeft % 60).toString().padStart(2, '0')}
                  </div>
                  <div className="text-[10px] uppercase font-bold tracking-widest text-primary">Descanso en curso</div>
                </div>
              </div>

              <div className="flex items-center space-x-2">
                <button 
                  onClick={() => adjustTimer(-10)}
                  className="p-2 bg-white/5 hover:bg-white/10 rounded-lg text-white/50 transition-colors"
                >
                  -10s
                </button>
                <button 
                  onClick={() => adjustTimer(10)}
                  className="p-2 bg-white/5 hover:bg-white/10 rounded-lg text-white/50 transition-colors"
                >
                  +10s
                </button>
                <button 
                  onClick={stopTimer}
                  className="p-3 bg-red-500/10 hover:bg-red-500 text-red-500 hover:text-white rounded-xl transition-all"
                >
                  <TimerOff size={20} />
                </button>
              </div>
            </div>
          </motion.div>
        )}
      </AnimatePresence>

      <ConfirmationModal 
        isOpen={showDeleteConfirm}
        onClose={() => setShowDeleteConfirm(false)}
        onConfirm={deleteWorkout}
        title="¿Eliminar esta Rutina?"
        message="Esta acción borrará permanentemente la rutina de tu biblioteca y no podrás recuperarla."
        confirmText="Sí, eliminar"
        cancelText="Volver atrás"
      />
    </div>
  );
};

export default WorkoutEditor;
