import { useState, useEffect } from 'react';
import { useNavigate, useSearchParams } from 'react-router-dom';
import { supabase } from '../api/supabase';
import { motion, AnimatePresence, Reorder } from 'framer-motion';
import { Plus, Trash2, Check, ArrowLeft, Save, Dumbbell, Loader2, Timer, ChevronDown, Info, Lightbulb, Activity, TimerOff, GripVertical } from 'lucide-react';
import type { Exercise } from '../types';
import ExercisePicker from '../components/workout/ExercisePicker';
import AutoRoutineGenerator from '../components/workout/AutoRoutineGenerator';
import MediaModal from '../components/shared/MediaModal';
import ConfirmationModal from '../components/shared/ConfirmationModal';
import { Helmet } from 'react-helmet-async';
import { useNotification } from '../context/NotificationContext';

interface WorkoutExerciseState {
  id: string;
  exercise: Exercise;
  sets: {
    weight: string;
    reps: string;
    completed: boolean;
  }[];
}

const WorkoutEditor = () => {
  const navigate = useNavigate();
  const [name, setName] = useState('Nuevo Entrenamiento');
  const [exercises, setExercises] = useState<WorkoutExerciseState[]>([]);
  const [showPicker, setShowPicker] = useState(false);
  const [showAutoGenerator, setShowAutoGenerator] = useState(false);
  const [showDeleteConfirm, setShowDeleteConfirm] = useState(false);
  const [saving, setSaving] = useState(false);
  const [loading, setLoading] = useState(false);
  const [isTemplate, setIsTemplate] = useState(false);
  const [expandedEx, setExpandedEx] = useState<string | null>(null); // Use a unique string key
  
  // Timer State
  const [timeLeft, setTimeLeft] = useState<number | null>(null);
  const [isTimerActive, setIsTimerActive] = useState(false);
  const [timerDuration] = useState(60);
  
  // Fullscreen Preview State
  const [fsMedia, setFsMedia] = useState<{ url: string; title: string } | null>(null);
  
  const [searchParams] = useSearchParams();
  const { showToast } = useNotification();

  useEffect(() => {
    const templateId = searchParams.get('templateId');
    const editId = searchParams.get('editId');
    const isNewTemplate = searchParams.get('template') === 'true';
    
    if (isNewTemplate) {
      setIsTemplate(true);
      setName('Nueva Rutina');
    }

    if (editId) {
      loadWorkoutData(editId, true);
    } else if (templateId) {
      loadWorkoutData(templateId, false);
    }
  }, [searchParams]);

  const handleAutoGenerated = (newExercises: Exercise[]) => {
    const formatted = newExercises.map(ex => ({
      id: crypto.randomUUID(),
      exercise: ex,
      sets: [{ weight: '', reps: '', completed: false }]
    }));
    setExercises([...exercises, ...formatted]);
    setShowAutoGenerator(false);
  };

  // Timer Interval
  useEffect(() => {
    let interval: any;
    if (isTimerActive && timeLeft !== null && timeLeft > 0) {
      interval = setInterval(() => {
        setTimeLeft(prev => (prev !== null && prev > 0) ? prev - 1 : 0);
      }, 1000);
    } else if (timeLeft === 0) {
      setIsTimerActive(false);
      playTimerEndSound();
    }
    return () => clearInterval(interval);
  }, [isTimerActive, timeLeft]);

  const playTimerEndSound = () => {
    try {
      const audio = new Audio('https://assets.mixkit.co/active_storage/sfx/2869/2869-preview.mp3');
      audio.volume = 0.5;
      audio.play();
      
      // Haptic feedback if available
      if (window.navigator.vibrate) {
        window.navigator.vibrate([200, 100, 200]);
      }
    } catch (e) {
      console.warn('Audio play failed', e);
    }
  };

  const loadWorkoutData = async (id: string, isEditing: boolean) => {
    setLoading(true);
    const { data: workout, error: workoutError } = await supabase
      .from('workouts')
      .select('*, workout_exercises(*, exercise:exercises(*), sets(*))')
      .eq('id', id)
      .single();

    if (workoutError || !workout) {
      console.error('Error loading workout data:', workoutError);
      return;
    }

    setName(workout.name);
    setIsTemplate(workout.is_template);
    
    if (!isEditing) {
      setIsTemplate(false);
    }

    interface DBSet { weight: number, reps: number, completed: boolean, order_index: number }

    const loadedExercises: WorkoutExerciseState[] = workout.workout_exercises
      .sort((a: any, b: any) => a.order_index - b.order_index)
      .map((we: any) => ({
        id: we.id,
        exercise: Array.isArray(we.exercise) ? we.exercise[0] : we.exercise,
        sets: (we.sets || []).sort((a: DBSet, b: DBSet) => a.order_index - b.order_index).map((s: DBSet) => ({
          weight: s.weight ? s.weight.toString() : '',
          reps: s.reps ? s.reps.toString() : '',
          completed: s.completed
        }))
      }));

    setExercises(loadedExercises);
    setLoading(false);
  };

  const addExercise = (exercise: Exercise) => {
    setExercises([...exercises, {
      id: crypto.randomUUID(),
      exercise,
      sets: [{ weight: '', reps: '', completed: false }]
    }]);
    setShowPicker(false);
  };

  const removeExercise = (index: number) => {
    setExercises(exercises.filter((_, i) => i !== index));
  };

  const addSet = (exerciseIndex: number) => {
    const newExercises = [...exercises];
    const lastSet = newExercises[exerciseIndex].sets[newExercises[exerciseIndex].sets.length - 1];
    newExercises[exerciseIndex].sets.push({
      weight: lastSet?.weight || '',
      reps: lastSet?.reps || '',
      completed: false
    });
    setExercises(newExercises);
  };

  const updateSet = (exerciseIndex: number, setIndex: number, field: keyof WorkoutExerciseState['sets'][0], value: string | boolean) => {
    const newExercises = [...exercises];
    const set = newExercises[exerciseIndex].sets[setIndex];
    if (field === 'completed') {
      set.completed = value as boolean;
    } else if (field === 'weight') {
      set.weight = value as string;
    } else if (field === 'reps') {
      set.reps = value as string;
    }
    setExercises(newExercises);
  };

  const toggleSetComplete = (exerciseIndex: number, setIndex: number) => {
    const newExercises = [...exercises];
    const isNowCompleted = !newExercises[exerciseIndex].sets[setIndex].completed;
    newExercises[exerciseIndex].sets[setIndex].completed = isNowCompleted;
    setExercises(newExercises);

    // Auto-trigger timer if completing a set
    if (isNowCompleted && !isTemplate) {
      startTimer();
    }
  };

  const startTimer = (seconds = timerDuration) => {
    setTimeLeft(seconds);
    setIsTimerActive(true);
  };

  const stopTimer = () => {
    setIsTimerActive(false);
    setTimeLeft(null);
  };

  const adjustTimer = (seconds: number) => {
    setTimeLeft(prev => (prev !== null ? Math.max(0, prev + seconds) : seconds));
    if (!isTimerActive) setIsTimerActive(true);
  };

  const saveWorkout = async () => {
    if (exercises.length === 0) return;
    setSaving(true);
    
    try {
      const { data: { user } } = await supabase.auth.getUser();
      if (!user) throw new Error('Not authenticated');

      const editId = searchParams.get('editId');
      let workoutId = editId;

      // 1. Create or Update Workout
      if (editId) {
        const { error: updateError } = await supabase
          .from('workouts')
          .update({
            name,
            is_template: isTemplate,
            completed_at: isTemplate ? null : new Date().toISOString()
          })
          .eq('id', editId);
        
        if (updateError) throw updateError;

        // Delete existing exercises/sets to re-insert updated ones (cleanest way to handle adds/removes)
        const { error: deleteError } = await supabase
          .from('workout_exercises')
          .delete()
          .eq('workout_id', editId);
        
        if (deleteError) throw deleteError;
      } else {
        const { data: newWorkout, error: workoutError } = await supabase
          .from('workouts')
          .insert({
            user_id: user.id,
            name,
            started_at: new Date().toISOString(),
            completed_at: isTemplate ? null : new Date().toISOString(),
            is_template: isTemplate
          })
          .select()
          .single();

        if (workoutError) throw workoutError;
        workoutId = newWorkout.id;
      }

      // 2. Create Workout Exercises and Sets
      for (let i = 0; i < exercises.length; i++) {
        const { data: we, error: weError } = await supabase
          .from('workout_exercises')
          .insert({
            workout_id: workoutId,
            exercise_id: exercises[i].exercise.id,
            order_index: i
          })
          .select()
          .single();

        if (weError) throw weError;

        const setsToInsert = exercises[i].sets.map((set, setIndex) => ({
          workout_exercise_id: we.id,
          weight: parseFloat(set.weight) || 0,
          reps: parseInt(set.reps) || 0,
          completed: set.completed,
          order_index: setIndex
        }));

        const { error: setsError } = await supabase
          .from('sets')
          .insert(setsToInsert);

        if (setsError) throw setsError;
      }

      showToast(isTemplate ? 'Rutina guardada con éxito' : 'Entrenamiento guardado con éxito', 'success');
      navigate(isTemplate ? '/routines' : '/');
    } catch (err) {
      console.error(err);
      showToast('Error al guardar', 'error');
    } finally {
      setSaving(false);
    }
  };

  const deleteWorkout = async () => {
    const editId = searchParams.get('editId');
    if (!editId) return;
    
    setSaving(true);
    try {
      const { error } = await supabase
        .from('workouts')
        .delete()
        .eq('id', editId);
      
      if (error) throw error;
      showToast('Rutina eliminada', 'success');
      navigate('/routines');
    } catch (err) {
      console.error(err);
      showToast('Error al eliminar', 'error');
    } finally {
      setSaving(false);
      setShowDeleteConfirm(false);
    }
  };

  return (
    <div className="min-h-screen bg-background pb-32">
      <Helmet>
        <title>{name} | FitPlanner Pro</title>
        <meta name="description" content="Registra tus ejercicios, series y repeticiones. Controla tu progreso en tiempo real." />
      </Helmet>
      {/* Header */}
      <div className="fixed top-0 left-0 right-0 glass-card rounded-none border-t-0 p-4 z-40 flex justify-between items-center">
        <button onClick={() => navigate(-1)} className="p-2 bg-white/5 rounded-xl">
          <ArrowLeft size={20} />
        </button>
        <h1 className="flex-1">
          <input 
            value={name}
            onChange={(e) => setName(e.target.value)}
            placeholder={isTemplate ? "Nombre de la Rutina (ej. Pierna)" : "Nombre del Entrenamiento"}
            className="w-full bg-transparent text-center font-black italic uppercase tracking-tighter outline-none focus:text-primary px-4"
            aria-label={isTemplate ? "Nombre de la rutina" : "Nombre del entrenamiento"}
          />
        </h1>
        <div className="flex items-center space-x-2">
          {searchParams.get('editId') && (
            <button 
              onClick={() => setShowDeleteConfirm(true)} 
              disabled={saving}
              className="p-2.5 rounded-xl bg-red-500/10 text-red-500 hover:bg-red-500 hover:text-white transition-all shadow-lg"
              title="Eliminar rutina"
            >
              <Trash2 size={20} />
            </button>
          )}
          <button 
            onClick={saveWorkout} 
            disabled={saving || exercises.length === 0}
            className={`p-2.5 rounded-xl bg-primary text-black hover:scale-105 active:scale-95 transition-all shadow-lg ${saving ? 'animate-pulse' : ''}`}
            title="Guardar cambios"
          >
            <Save size={20} />
          </button>
        </div>
      </div>

      {loading ? (
        <div className="flex flex-col items-center justify-center min-h-[60vh] space-y-4">
          <Loader2 size={48} className="text-primary animate-spin" />
          <p className="text-white/30 font-bold uppercase tracking-widest text-xs">Cargando datos...</p>
        </div>
      ) : (
        <Reorder.Group 
          axis="y" 
          values={exercises} 
          onReorder={setExercises}
          className="pt-20 px-4 space-y-6 max-w-lg mx-auto"
        >
          <AnimatePresence>
            {exercises.map((ex, exIdx) => (
              <Reorder.Item 
                key={ex.id} 
                value={ex}
                className="relative group transition-all"
              >
                <motion.div 
                  initial={{ opacity: 0, scale: 0.95 }}
                  animate={{ opacity: 1, scale: 1 }}
                  exit={{ opacity: 0, scale: 0.95 }}
                  className="glass-card overflow-hidden flex"
                >
                  {/* Grip Handle */}
                  <div className="w-10 flex items-center justify-center bg-white/5 cursor-grab active:cursor-grabbing text-white/10 hover:text-primary/50 transition-colors border-r border-white/5">
                    <GripVertical size={20} />
                  </div>

                  <div className="flex-1 flex flex-col">
                    <div 
                      className="p-4 bg-white/5 flex justify-between items-center cursor-pointer hover:bg-white/10 transition-colors"
                      onClick={() => {
                        setExpandedEx(expandedEx === ex.id ? null : ex.id);
                      }}
                    >
                      <div className="flex items-center space-x-3">
                        {ex.exercise.video_url || ex.exercise.image_url ? (
                          <div className="w-14 h-14 rounded-xl overflow-hidden shrink-0 bg-white/5 border border-white/10 relative group/media">
                            {ex.exercise.video_url ? (
                              <video src={ex.exercise.video_url} autoPlay loop muted playsInline className="w-full h-full object-cover" />
                            ) : ex.exercise.image_url?.includes('.mp4') || ex.exercise.image_url?.includes('.webm') ? (
                              <video src={ex.exercise.image_url} autoPlay loop muted playsInline className="w-full h-full object-cover" />
                            ) : (
                              <img src={ex.exercise.image_url!} alt={ex.exercise.name} className="w-full h-full object-cover group-hover:scale-110 transition-transform" />
                            )}
                          </div>
                        ) : (
                          <div className="w-14 h-14 rounded-xl shrink-0 bg-white/5 border border-white/10 flex items-center justify-center text-white/10">
                            <Dumbbell size={20} />
                          </div>
                        )}
                        <div className="max-w-[120px] sm:max-w-[200px]">
                          <h3 className="font-black italic uppercase tracking-tight text-primary leading-tight truncate">{ex.exercise.name}</h3>
                          <p className="text-[10px] text-white/30 uppercase font-bold">{ex.exercise.category}</p>
                        </div>
                      </div>
                      <div className="flex items-center space-x-2">
                        <button 
                          onClick={(e) => {
                            e.stopPropagation();
                            removeExercise(exIdx);
                          }} 
                          className="p-2 text-white/10 hover:text-red-400 transition-colors"
                        >
                          <Trash2 size={16} />
                        </button>
                        <div className={`p-1 transition-transform duration-300 ${expandedEx === ex.id ? 'rotate-180' : ''}`}>
                          <ChevronDown size={18} className="text-white/20" />
                        </div>
                      </div>
                    </div>

                    <AnimatePresence initial={false}>
                      {expandedEx === ex.id && (
                        <motion.div
                          initial={{ height: 0, opacity: 0 }}
                          animate={{ height: 'auto', opacity: 1 }}
                          exit={{ height: 0, opacity: 0 }}
                          transition={{ duration: 0.3, ease: 'easeInOut' }}
                          className="overflow-hidden"
                        >
                          {/* Large Media Preview */}
                          {ex.exercise.image_url && (
                            <div 
                              className="aspect-video w-full relative flex items-center justify-center bg-black/20 cursor-expand hover:bg-black/30 transition-all group/expand border-y border-white/5"
                              onClick={(e) => {
                                e.stopPropagation();
                                setFsMedia({ 
                                  url: ex.exercise.video_url || ex.exercise.image_url || '', 
                                  title: ex.exercise.name 
                                });
                              }}
                            >
                              {/* Video detection */}
                              {ex.exercise.video_url ? (
                                <video 
                                  src={ex.exercise.video_url} 
                                  autoPlay 
                                  loop 
                                  muted 
                                  playsInline 
                                  controls
                                  className="relative z-10 w-full h-full object-contain"
                                />
                              ) : (ex.exercise.image_url?.includes('.mp4') || 
                                ex.exercise.image_url?.includes('.webm') || 
                                ex.exercise.image_url?.includes('video') ||
                                ex.exercise.image_url?.includes('giphy')) ? (
                                <video 
                                  src={ex.exercise.image_url} 
                                  autoPlay 
                                  loop 
                                  muted 
                                  playsInline 
                                  controls
                                  className="relative z-10 w-full h-full object-contain"
                                />
                              ) : (
                                <img 
                                  src={ex.exercise.image_url || ''} 
                                  alt={ex.exercise.name} 
                                  className="relative z-10 w-full h-full object-contain" 
                                />
                              )}
                            </div>
                          )}

                          {/* Technical Detail Section (EDB-v2) */}
                          {(ex.exercise.instructions || ex.exercise.tips || ex.exercise.male_activation_url) && (
                            <div className="p-4 bg-white/[0.02] border-b border-white/5 space-y-6">
                              
                              {/* Muscle Map & Difficulty */}
                              <div className="flex gap-4 items-start">
                                <div className="flex-1 space-y-3">
                                  <div className="flex items-center space-x-2 text-primary">
                                    <Activity size={14} />
                                    <span className="text-[10px] font-black uppercase tracking-widest italic">Músculos Activados</span>
                                  </div>
                                  <div className="aspect-square w-full rounded-2xl bg-black/40 border border-white/5 overflow-hidden relative group/muscle">
                                    <img 
                                      src={ex.exercise.gender === 'female' ? ex.exercise.female_activation_url! : ex.exercise.male_activation_url!} 
                                      className="w-full h-full object-contain"
                                    />
                                    <div className="absolute inset-0 bg-gradient-to-t from-black/60 to-transparent" />
                                    <div className="absolute bottom-2 left-2 px-2 py-0.5 bg-primary/20 backdrop-blur-md rounded-full border border-primary/20">
                                      <span className="text-[8px] font-bold text-primary uppercase tracking-tighter">
                                        {ex.exercise.difficulty || 'Nivel Estándar'}
                                      </span>
                                    </div>
                                  </div>
                                </div>

                                {/* Instructions List */}
                                <div className="flex-[1.5] space-y-3">
                                  <div className="flex items-center space-x-2 text-white/50">
                                    <Info size={14} />
                                    <span className="text-[10px] font-black uppercase tracking-widest italic">Instrucciones</span>
                                  </div>
                                  <div className="space-y-2 max-h-[180px] overflow-y-auto custom-scrollbar pr-2">
                                    {ex.exercise.instructions ? (ex.exercise.instructions as string[]).map((step, idx) => (
                                      <div key={idx} className="flex space-x-2">
                                        <span className="text-primary font-bold text-[10px] mt-0.5">{idx + 1}.</span>
                                        <p className="text-[10px] text-white/60 leading-relaxed font-medium">{step}</p>
                                      </div>
                                    )) : (
                                      <p className="text-[10px] text-white/20 italic">No hay instrucciones registradas.</p>
                                    )}
                                  </div>
                                </div>
                              </div>

                              {/* Expert Tips */}
                              {ex.exercise.tips && (ex.exercise.tips as string[]).length > 0 && (
                                <div className="p-3 bg-primary/5 rounded-2xl border border-primary/10">
                                  <div className="flex items-center space-x-2 text-primary mb-2">
                                    <Lightbulb size={14} />
                                    <span className="text-[10px] font-black uppercase tracking-widest italic">Tips del Experto</span>
                                  </div>
                                  <div className="space-y-1.5">
                                    {(ex.exercise.tips as string[]).map((tip, idx) => (
                                      <div key={idx} className="flex items-start space-x-2">
                                        <span className="w-1 h-1 rounded-full bg-primary mt-1.5 shrink-0" />
                                        <p className="text-[9px] text-white/70 italic leading-tight">{tip}</p>
                                      </div>
                                    ))}
                                  </div>
                                </div>
                              )}
                            </div>
                          )}

                          {/* Sets Section */}
                          <div className="p-4 space-y-2">
                            <div className="grid grid-cols-4 gap-2 text-[10px] uppercase font-bold text-white/30 mb-1 px-2">
                              <div className="text-center">Serie</div>
                              <div className="text-center">kg</div>
                              <div className="text-center">Reps</div>
                              <div className="text-center">Listo</div>
                            </div>

                            {ex.sets.map((set, setIdx) => (
                              <div key={setIdx} className={`grid grid-cols-4 gap-2 items-center p-2 rounded-lg transition-colors ${set.completed ? 'bg-primary/5' : 'bg-white/5'}`}>
                                <div className="text-center font-bold italic text-white/30">{setIdx + 1}</div>
                                <input
                                  type="number"
                                  placeholder="0"
                                  className="bg-white/5 border border-white/10 rounded-lg py-1 px-2 text-center outline-none focus:border-primary/50"
                                  value={set.weight}
                                  onChange={(e) => updateSet(exIdx, setIdx, 'weight', e.target.value)}
                                />
                                <input
                                  type="number"
                                  placeholder="0"
                                  className="bg-white/5 border border-white/10 rounded-lg py-1 px-2 text-center outline-none focus:border-primary/50"
                                  value={set.reps}
                                  onChange={(e) => updateSet(exIdx, setIdx, 'reps', e.target.value)}
                                />
                                <button 
                                  onClick={() => toggleSetComplete(exIdx, setIdx)}
                                  className={`flex justify-center p-1 rounded-lg transition-all ${set.completed ? 'bg-primary text-black' : 'bg-white/5 text-white/20'}`}
                                >
                                  <Check size={16} />
                                </button>
                              </div>
                            ))}

                            <button 
                              onClick={() => addSet(exIdx)}
                              className="w-full py-2 bg-white/5 border border-white/10 rounded-xl text-xs font-bold uppercase tracking-widest text-white/30 hover:bg-white/10 transition-colors"
                            >
                              + Añadir Serie
                            </button>
                          </div>
                        </motion.div>
                      )}
                    </AnimatePresence>
                  </div>
                </motion.div>
              </Reorder.Item>
            ))}
          </AnimatePresence>
            <div className="flex gap-3">
              <button
                onClick={() => setShowPicker(true)}
                className="flex-1 glass-card p-4 flex items-center justify-center space-x-2 border-primary/20 hover:border-primary/50 transition-all text-primary"
              >
                <Plus size={20} />
                <span className="font-bold uppercase italic text-xs">Añadir Ejercicio</span>
              </button>
              <button
                onClick={() => setShowAutoGenerator(true)}
                className="flex-1 glass-card p-4 flex items-center justify-center space-x-2 border-primary/20 hover:border-primary/50 transition-all text-primary"
              >
                <Loader2 size={20} className="text-primary hover:rotate-180 transition-transform" />
                <span className="font-bold uppercase italic text-xs">Auto-Generar</span>
              </button>
            </div>
          </Reorder.Group>
        )
      }

      <AnimatePresence>
        {showPicker && (
          <ExercisePicker 
            onSelect={addExercise}
            onClose={() => setShowPicker(false)}
          />
        )}
        {showAutoGenerator && (
          <AutoRoutineGenerator 
            onGenerated={handleAutoGenerated}
            onClose={() => setShowAutoGenerator(false)}
          />
        )}
      </AnimatePresence>

      {/* Fullscreen Media Modal */}
      <MediaModal 
        isOpen={!!fsMedia}
        url={fsMedia?.url || ''}
        title={fsMedia?.title || ''}
        onClose={() => setFsMedia(null)}
      />

      {/* Floating Rest Timer Component */}
      <AnimatePresence>
        {timeLeft !== null && (
          <motion.div
            initial={{ y: 100, opacity: 0 }}
            animate={{ y: 0, opacity: 1 }}
            exit={{ y: 100, opacity: 0 }}
            className="fixed bottom-24 left-4 right-4 z-50 flex justify-center"
          >
            <div className="glass-card shadow-2xl border-primary/20 bg-black/80 backdrop-blur-2xl px-6 py-4 flex items-center space-x-6 min-w-[300px] justify-between">
              <div className="flex items-center space-x-4">
                <div className="relative">
                  <div className="w-12 h-12 rounded-full border-2 border-white/5 flex items-center justify-center">
                    <Timer className={isTimerActive ? "text-primary animate-pulse" : "text-white/20"} size={24} />
                  </div>
                  {/* Simple Progress Ring effect */}
                  <svg className="absolute inset-0 w-12 h-12 -rotate-90">
                    <circle 
                      cx="24" cy="24" r="22" 
                      fill="transparent" 
                      stroke="currentColor" 
                      strokeWidth="2" 
                      strokeDasharray={2 * Math.PI * 22}
                      strokeDashoffset={(1 - (timeLeft / timerDuration)) * 2 * Math.PI * 22}
                      className="text-primary transition-all duration-300"
                    />
                  </svg>
                </div>
                <div>
                  <div className="text-2xl font-black italic tracking-tighter text-white tabular-nums">
                    {Math.floor(timeLeft / 60)}:{(timeLeft % 60).toString().padStart(2, '0')}
                  </div>
                  <div className="text-[10px] uppercase font-bold tracking-widest text-primary">Descanso en curso</div>
                </div>
              </div>

              <div className="flex items-center space-x-2">
                <button 
                  onClick={() => adjustTimer(-10)}
                  className="p-2 bg-white/5 hover:bg-white/10 rounded-lg text-white/50 transition-colors"
                >
                  -10s
                </button>
                <button 
                  onClick={() => adjustTimer(10)}
                  className="p-2 bg-white/5 hover:bg-white/10 rounded-lg text-white/50 transition-colors"
                >
                  +10s
                </button>
                <button 
                  onClick={stopTimer}
                  className="p-3 bg-red-500/10 hover:bg-red-500 text-red-500 hover:text-white rounded-xl transition-all"
                >
                  <TimerOff size={20} />
                </button>
              </div>
            </div>
          </motion.div>
        )}
      </AnimatePresence>

      <ConfirmationModal 
        isOpen={showDeleteConfirm}
        onClose={() => setShowDeleteConfirm(false)}
        onConfirm={deleteWorkout}
        title="¿Eliminar esta Rutina?"
        message="Esta acción borrará permanentemente la rutina de tu biblioteca y no podrás recuperarla."
        confirmText="Sí, eliminar"
        cancelText="Volver atrás"
      />
    </div>
  );
};

export default WorkoutEditor;
